import React from 'react'

export const metadata = {
    title: 'About',
    description: 'Generated by create next app',
  }

export default function AboutLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
    <>
    <nav> About navbar</nav>
    <main className=' min-h-screen grid place-content-center bg-gray-700'>
        {children}
    </main>
    </>
  )
}